version: '2.1'

services:
  docker-flask-postgresql-microservice:
    image: docker-flask-postgresql-microservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
