version: '2'
services:
    web:
        build: ./compose_flask
        ports:
            - "5000:5000"
        volumes:
            - ./compose_flask:/code
        depends_on:
            - postgres
    postgres:
        image: postgres
        restart: always